name: pub_server
version: 0.1.6-dev
description: Re-usable components for creating a custom Dart package server.
homepage: https://github.com/dart-lang/pub_server

environment:
  sdk: ^3.3.0

dependencies:
  http_parser: ^4.0.2
  logging: ^1.2.0
  mime: ^1.0.5
  pub_semver: ^2.1.4
  shelf: ^1.4.1
  stream_transform: ^2.1.0
  yaml: ^3.1.2

dev_dependencies:
  archive: ^3.4.10 
  args: ^2.5.0
  http: ^1.2.1
  path: ^1.9.0
  pedantic: ^1.2.0
  test: ^1.3.0
